### ISSUE TITLE
Auto-generate tests for each Controller

### ISSUE THREAD

**Issue by yosbelms** [petkopara/PetkoparaCrudGeneratorBundle#32]
To write tests for each controllers-action is a common use case now day. Will be useful if PetkoparaCrudGenerator could generate test stubs that tests the generated Controllers.

**Comment by petkopara** [comment]
Can reference the typos that you found

**Comment by yosbelms** [comment]
@petkopara I mean fixing my own typos I wrote when opening the issue.

**Comment by petkopara** [comment]
fixed generated tests in v3.0.5
