### ISSUE TITLE
Create, Edit, Delete buttons not found

### ISSUE THREAD

**Issue by devkbsc** [petkopara/PetkoparaCrudGeneratorBundle#42]
Hello, 
After a crud generation, i couldn't find the these following buttons on seeing the examples in your documentation on this page 

https://github.com/petkopara/PetkoparaCrudGeneratorBundle

I couldn't display the screen capture here! so i share the link of my drive 

https://drive.google.com/file/d/0B-ObBUQB7TeIUzlyRzZ3dXA1S2s/view?usp=sharing

Did i miss anything?

**Comment by petkopara** [comment]
Hi @devkbsc, 
From the shared image looks like you run the generator with the option --without-write, so the code for write actions is not generated.

**Comment by devkbsc** [comment]
Exactly! It works now! thanks a lot!
