### ISSUE TITLE
Where does a beginner start?

### ISSUE THREAD

**Issue by ssjindy** [petkopara/PetkoparaCrudGeneratorBundle#51]
I only became aware of Symfony after discovering this CRUD generator.  So I am a rank beginner with both.

After I figured out how to install and configure everything, I got to this point:

php bin/console petkopara:generate:crud

and the documentation tells me to 'follow the prompts'.

First thing is to 'give the name of the existing entity'.  So, what would that be?  I had assumed the starting point would be to input the name of a database table for which I wanted the CRUD generated.  Apparently not.  

Where do I turn to fill in the blanks?  It is not apparent what the starting point is, but apparently I construct 'existing entities' somehow, then reference those.  But where does the process start? That's omitted from the steps listed.

**Comment by petkopara** [comment]
Hi @ssjindy, 
you could create your entity with the following comand:
`php bin/console doctrine:generate:entity` 
and follow the wizard. 
This command will create you a file under Entity dir. 
After that you could update your database tables with this command: 
`php bin/console doctrine:schema:update --force`
and then you can use the Crud bundle.

**Comment by ssjindy** [comment]
Remember, I'm really new with this.  'use the CRUD bundle' means ?

I fumbled around and managed to generate something but I'm not sure what.  Feels like walking through a dark room and bumping into furniture:  "What was that?'

![petkopara2](https://user-images.githubusercontent.com/17769821/31722284-b25afd32-b3e9-11e7-863c-5c20370af19c.png)

No signs of anything that look like the two screenshots of the main write up.  I expected that running:
http://127.0.0.1:8000
would do that.

All I can achieve is:

Welcome to Symfony 3.3.10

Your application is now ready. You can start working on it at: I:\projects\petkopara\
